name: build-service-credentials
credentials:
 - name: kube_config
   source:
     path: "/Users/anandrao/.kube/config"
   destination:
     path: "/root/.kube/config"
   destination:
     path: "/cnab/app/cert/ca.crt"